'use strict';

/**
 * Unified error codes used across the WebSocket system.
 * Keep values stable for client compatibility.
 */
const ErrorCodes = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_SCHEMA: 'INVALID_SCHEMA',
  INVALID_FIELD_TYPE: 'INVALID_FIELD_TYPE',
  MISSING_FIELD: 'MISSING_FIELD',
  MISSING_TYPE: 'MISSING_TYPE',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_ACK_TYPE: 'INVALID_ACK_TYPE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  PERSISTENCE_ERROR: 'PERSISTENCE_ERROR',
  REPLAY_ERROR: 'REPLAY_ERROR',
  SYNC_ERROR: 'SYNC_ERROR',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RECIPIENT_BUFFER_FULL: 'RECIPIENT_BUFFER_FULL',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  MISSING_ROOM_ID: 'MISSING_ROOM_ID',
  CREATE_FAILED: 'CREATE_FAILED',
  JOIN_FAILED: 'JOIN_FAILED',
  LEAVE_FAILED: 'LEAVE_FAILED',
  MISSING_CONTENT: 'MISSING_CONTENT',
  CONTENT_TOO_LONG: 'CONTENT_TOO_LONG',
  BROADCAST_FAILED: 'BROADCAST_FAILED',
  INVALID_LAST_MESSAGE_ID: 'INVALID_LAST_MESSAGE_ID',
  CONNECTION_LIMIT: 'CONNECTION_LIMIT',
  /** Phase 1: NACK contract codes (stable for client) */
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = ErrorCodes;
