'use strict';

/**
 * MOVED IN PHASE 2 — NO LOGIC CHANGE
 * Message type constants extracted from websocket/router.js verbatim
 * 
 * Supported message types
 * @enum {string}
 */
const MessageType = {
  // Protocol negotiation (must be first message)
  HELLO: 'HELLO',
  // Direct messaging
  MESSAGE_SEND: 'MESSAGE_SEND',
  MESSAGE_ACK: 'MESSAGE_ACK',
  MESSAGE_NACK: 'MESSAGE_NACK',
  DELIVERY_STATUS: 'DELIVERY_STATUS',
  MESSAGE_READ: 'MESSAGE_READ',
  MESSAGE_READ_CONFIRM: 'MESSAGE_READ_CONFIRM',
  MESSAGE_DELIVERED_CONFIRM: 'MESSAGE_DELIVERED_CONFIRM',
  MESSAGE_REPLAY: 'MESSAGE_REPLAY',
  STATE_SYNC: 'STATE_SYNC',
  // Message mutations (edit/delete) — Phase 2 WS protocol
  MESSAGE_EDIT: 'MESSAGE_EDIT',
  MESSAGE_DELETE: 'MESSAGE_DELETE',
  MESSAGE_MUTATION: 'MESSAGE_MUTATION',
  MESSAGE_MUTATION_ACK: 'MESSAGE_MUTATION_ACK',
  // Reconnect resync
  RESUME: 'RESUME',
  // Presence
  PRESENCE_PING: 'PRESENCE_PING',
  // General
  CLIENT_ACK: 'CLIENT_ACK',
  PING: 'PING',
  // Room messaging (Phase 3A/3B: groups with RBAC)
  ROOM_CREATE: 'ROOM_CREATE',
  ROOM_JOIN: 'ROOM_JOIN',
  ROOM_LEAVE: 'ROOM_LEAVE',
  ROOM_MESSAGE: 'ROOM_MESSAGE',
  ROOM_INFO: 'ROOM_INFO',
  ROOM_LIST: 'ROOM_LIST',
  ROOM_MEMBERS: 'ROOM_MEMBERS',
  ROOM_UPDATE_META: 'ROOM_UPDATE_META',
  ROOM_ADD_MEMBERS: 'ROOM_ADD_MEMBERS',
  ROOM_REMOVE_MEMBER: 'ROOM_REMOVE_MEMBER',
  ROOM_SET_ROLE: 'ROOM_SET_ROLE',
  ROOM_DELETE: 'ROOM_DELETE',
  // Server → Client room events
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_MEMBERS_UPDATED: 'ROOM_MEMBERS_UPDATED',
  ROOM_DELETED: 'ROOM_DELETED',
  ROOMS_SNAPSHOT: 'ROOMS_SNAPSHOT',
  TYPING_START: 'TYPING_START',
  TYPING_STOP: 'TYPING_STOP',
};

module.exports = MessageType;
